// <auto-generated />
using System;
using Condolio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Condolio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CondolioDbContext))]
    [Migration("20260831235003_AdminMiembro")]
    partial class AdminMiembro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Condolio.Domain.Accesos.PaseAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CreadoPorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CreadoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Patente")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("PrimerUsoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TipoPase")
                        .HasColumnType("int");

                    b.Property<int>("TipoVisita")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UsosCount")
                        .HasColumnType("int");

                    b.Property<int>("UsosMax")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidoHastaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Vehiculo")
                        .HasColumnType("int");

                    b.Property<string>("VisitanteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("AdministradorId", "ConsorcioId", "Estado");

                    b.ToTable("PasesAcceso");
                });

            modelBuilder.Entity("Condolio.Domain.Accesos.RegistroVisita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentoVisitante")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EgresoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("IngresoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("PaseAccesoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Patente")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RegistradoPorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RegistradoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("TipoVisita")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Vehiculo")
                        .HasColumnType("int");

                    b.Property<string>("VisitanteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId", "UnidadId", "IngresoUtc");

                    b.ToTable("RegistrosVisita");
                });

            modelBuilder.Entity("Condolio.Domain.Amenidades.Amenidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DiasBloqueados")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagenesIds")
                        .HasColumnType("longtext");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("LimiteMensual")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxReservasPorUnidad")
                        .HasColumnType("int");

                    b.Property<string>("MensajeReserva")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("RequiereAprobacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Reservable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("ReservableDesde")
                        .HasColumnType("date");

                    b.Property<decimal?>("Tarifa")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("TieneCosto")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId");

                    b.ToTable("Amenidades");
                });

            modelBuilder.Entity("Condolio.Domain.Amenidades.AmenidadHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AbreMin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AmenidadId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CierraMin")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmenidadId");

                    b.HasIndex("AdministradorId", "AmenidadId");

                    b.ToTable("AmenidadHorarios");
                });

            modelBuilder.Entity("Condolio.Domain.Amenidades.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AmenidadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Importe")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nota")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ResueltaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SolicitanteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SolicitanteUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<Guid?>("UnidadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AmenidadId", "Inicio");

                    b.HasIndex("AdministradorId", "ConsorcioId", "Estado");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Condolio.Domain.Archivos.Adjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("OwnerTipo")
                        .HasColumnType("int");

                    b.Property<string>("RutaRelativa")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("SubidoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "OwnerTipo", "OwnerId");

                    b.ToTable("Adjuntos");
                });

            modelBuilder.Entity("Condolio.Domain.Billing.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CargoBaseMensual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("Condolio.Domain.Billing.PlanTramo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DesdeUnidad")
                        .HasColumnType("int");

                    b.Property<int?>("HastaUnidad")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecioPorUnidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanTramos");
                });

            modelBuilder.Entity("Condolio.Domain.Billing.Suscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<decimal>("ImporteMensual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProveedorSuscripcionId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProximoCobroUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TrialFinUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TrialInicioUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UnidadesFacturadas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("Condolio.Domain.Calendario.EventoCalendario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CreadoPorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CreadoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("FinUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NotificoComunidad")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("TodoElDia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId", "InicioUtc");

                    b.ToTable("EventosCalendario");
                });

            modelBuilder.Entity("Condolio.Domain.Comunicaciones.Anuncio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AutorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("varchar(8000)");

                    b.Property<DateTime?>("EventoFechaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Fijado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImagenesIds")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PublicadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId", "Fijado", "PublicadoUtc");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("Condolio.Domain.Comunicaciones.AnuncioComentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnuncioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AutorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("AdministradorId", "AnuncioId");

                    b.ToTable("AnuncioComentarios");
                });

            modelBuilder.Entity("Condolio.Domain.Comunicaciones.AnuncioLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnuncioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("AnuncioLikes");
                });

            modelBuilder.Entity("Condolio.Domain.Consorcios.Consorcio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cuit")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double");

                    b.Property<string>("Localidad")
                        .HasColumnType("longtext");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provincia")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.ToTable("Consorcios");
                });

            modelBuilder.Entity("Condolio.Domain.Contactos.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CreadoPorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CreadoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId", "Categoria");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("Condolio.Domain.Documentos.CarpetaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CarpetaPadreId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId", "CarpetaPadreId");

                    b.ToTable("CarpetasDocumento");
                });

            modelBuilder.Entity("Condolio.Domain.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CarpetaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Destacado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)");

                    b.Property<string>("RutaRelativa")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("SubidoPorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SubidoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UltimoAccesoUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId", "CarpetaId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("Condolio.Domain.Documentos.DocumentoAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("EsDescarga")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId", "DocumentoId");

                    b.ToTable("DocumentosAcceso");
                });

            modelBuilder.Entity("Condolio.Domain.Encuestas.Encuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Anonima")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AutorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CierreUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("ModoVotacion")
                        .HasColumnType("int");

                    b.Property<bool>("MultiplesOpciones")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PublicadaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "ConsorcioId", "Estado");

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("Condolio.Domain.Encuestas.OpcionEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EncuestaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId");

                    b.HasIndex("AdministradorId", "EncuestaId");

                    b.ToTable("OpcionesEncuesta");
                });

            modelBuilder.Entity("Condolio.Domain.Encuestas.VotoEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EncuestaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OpcionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId", "UsuarioId", "OpcionId")
                        .IsUnique();

                    b.ToTable("VotosEncuesta");
                });

            modelBuilder.Entity("Condolio.Domain.Notificaciones.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DestinatarioUsuarioId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Enlace")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime?>("FijadaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeidaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioUsuarioId", "LeidaUtc");

                    b.HasIndex("AdministradorId", "ConsorcioId", "LeidaUtc");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Condolio.Domain.Notificaciones.PreferenciasNotificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ComunidadApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ComunidadMail")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EdificioApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EdificioMail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EventosApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EventosMail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FinanzasApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FinanzasMail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SeguridadApp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SeguridadMail")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PreferenciasNotificacion");
                });

            modelBuilder.Entity("Condolio.Domain.Paqueteria.Paquete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EntregaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntregadoPorNombre")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("FotoRuta")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("LlegadaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegistradoPorNombre")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("RetiradoPorNombre")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Transportista")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UnidadNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId", "Estado", "LlegadaUtc");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Condolio.Domain.Personal.MiembroPersonal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("EsDispositivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("AdministradorId", "ConsorcioId");

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("Condolio.Domain.Personal.TurnoPorteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CredencialUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MiembroPersonalId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NotasCierre")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PersonalNombre")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId", "InicioUtc");

                    b.HasIndex("CredencialUsuarioId", "FinUtc");

                    b.ToTable("TurnosPorteria");
                });

            modelBuilder.Entity("Condolio.Domain.Residentes.Invitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvitadoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("UnidadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("AdministradorId", "ConsorcioId", "Estado");

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("Condolio.Domain.Residentes.MiembroJunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId", "UsuarioId", "Cargo")
                        .IsUnique();

                    b.ToTable("MiembrosJunta");
                });

            modelBuilder.Entity("Condolio.Domain.Tenancy.AdminMiembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AreasCsv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EsDueno")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsGeneral")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("AdminMiembros");
                });

            modelBuilder.Entity("Condolio.Domain.Tenancy.Administrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cuit")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Condolio.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ArchivadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AsignadoANombre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AsignadoAUsuarioId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("EstadoDesdeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("IncidenciaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("ReportadoPorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ReportadoPorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("ReportadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UltimaActividadUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UnidadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId", "Numero")
                        .IsUnique();

                    b.HasIndex("AdministradorId", "ConsorcioId", "Estado");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Condolio.Domain.Tickets.TicketComentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EsInterna")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("AdministradorId", "TicketId");

                    b.ToTable("TicketComentarios");
                });

            modelBuilder.Entity("Condolio.Domain.Tickets.TicketEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorNombre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ActorUsuarioId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("AdministradorId", "TicketId");

                    b.ToTable("TicketEventos");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.IncidenciaComentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IncidenciaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.HasIndex("AdministradorId", "IncidenciaId");

                    b.ToTable("IncidenciaComentarios");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.Unidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("AreaM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Coeficiente")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("ConsorcioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CuotaMantenimiento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Facturable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("InquilinosVenFinanzas")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Ocupacion")
                        .HasColumnType("int");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.Property<string>("Seccion")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsorcioId");

                    b.HasIndex("AdministradorId", "ConsorcioId");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadActividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActorUsuarioId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.HasIndex("AdministradorId", "UnidadId");

                    b.ToTable("UnidadActividades");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadIncidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("EscaladaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Severidad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.HasIndex("AdministradorId", "UnidadId");

                    b.ToTable("UnidadIncidencias");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadNota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AutorUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.HasIndex("AdministradorId", "UnidadId");

                    b.ToTable("UnidadNotas");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadPersona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EsContactoPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.HasIndex("AdministradorId", "UnidadId");

                    b.ToTable("UnidadPersonas");
                });

            modelBuilder.Entity("Condolio.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AdministradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoVerificacion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CodigoVerificacionExpiraUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Condolio.Domain.Amenidades.AmenidadHorario", b =>
                {
                    b.HasOne("Condolio.Domain.Amenidades.Amenidad", "Amenidad")
                        .WithMany("Horarios")
                        .HasForeignKey("AmenidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenidad");
                });

            modelBuilder.Entity("Condolio.Domain.Amenidades.Reserva", b =>
                {
                    b.HasOne("Condolio.Domain.Amenidades.Amenidad", "Amenidad")
                        .WithMany()
                        .HasForeignKey("AmenidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenidad");
                });

            modelBuilder.Entity("Condolio.Domain.Billing.PlanTramo", b =>
                {
                    b.HasOne("Condolio.Domain.Billing.Plan", "Plan")
                        .WithMany("Tramos")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Condolio.Domain.Billing.Suscripcion", b =>
                {
                    b.HasOne("Condolio.Domain.Tenancy.Administrador", "Administrador")
                        .WithOne("Suscripcion")
                        .HasForeignKey("Condolio.Domain.Billing.Suscripcion", "AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condolio.Domain.Billing.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Condolio.Domain.Comunicaciones.AnuncioComentario", b =>
                {
                    b.HasOne("Condolio.Domain.Comunicaciones.Anuncio", "Anuncio")
                        .WithMany("Comentarios")
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("Condolio.Domain.Comunicaciones.AnuncioLike", b =>
                {
                    b.HasOne("Condolio.Domain.Comunicaciones.Anuncio", "Anuncio")
                        .WithMany("Likes")
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("Condolio.Domain.Encuestas.OpcionEncuesta", b =>
                {
                    b.HasOne("Condolio.Domain.Encuestas.Encuesta", "Encuesta")
                        .WithMany("Opciones")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("Condolio.Domain.Encuestas.VotoEncuesta", b =>
                {
                    b.HasOne("Condolio.Domain.Encuestas.Encuesta", "Encuesta")
                        .WithMany("Votos")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("Condolio.Domain.Residentes.Invitacion", b =>
                {
                    b.HasOne("Condolio.Domain.Consorcios.Consorcio", "Consorcio")
                        .WithMany()
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("Condolio.Domain.Tickets.TicketComentario", b =>
                {
                    b.HasOne("Condolio.Domain.Tickets.Ticket", "Ticket")
                        .WithMany("Comentarios")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Condolio.Domain.Tickets.TicketEvento", b =>
                {
                    b.HasOne("Condolio.Domain.Tickets.Ticket", "Ticket")
                        .WithMany("Eventos")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.IncidenciaComentario", b =>
                {
                    b.HasOne("Condolio.Domain.Unidades.UnidadIncidencia", "Incidencia")
                        .WithMany("Comentarios")
                        .HasForeignKey("IncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidencia");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.Unidad", b =>
                {
                    b.HasOne("Condolio.Domain.Consorcios.Consorcio", "Consorcio")
                        .WithMany("Unidades")
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadActividad", b =>
                {
                    b.HasOne("Condolio.Domain.Unidades.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadIncidencia", b =>
                {
                    b.HasOne("Condolio.Domain.Unidades.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadNota", b =>
                {
                    b.HasOne("Condolio.Domain.Unidades.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadPersona", b =>
                {
                    b.HasOne("Condolio.Domain.Unidades.Unidad", "Unidad")
                        .WithMany("Personas")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Condolio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Condolio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condolio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Condolio.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Condolio.Domain.Amenidades.Amenidad", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Condolio.Domain.Billing.Plan", b =>
                {
                    b.Navigation("Tramos");
                });

            modelBuilder.Entity("Condolio.Domain.Comunicaciones.Anuncio", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Condolio.Domain.Consorcios.Consorcio", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Condolio.Domain.Encuestas.Encuesta", b =>
                {
                    b.Navigation("Opciones");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Condolio.Domain.Tenancy.Administrador", b =>
                {
                    b.Navigation("Suscripcion");
                });

            modelBuilder.Entity("Condolio.Domain.Tickets.Ticket", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.Unidad", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Condolio.Domain.Unidades.UnidadIncidencia", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
